// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq2YZFKY5rBVrKD2Tr8DnUPOveoKOM3UI',
    appId: '1:1032931526089:web:cf6922402d9bef22d8d418',
    messagingSenderId: '1032931526089',
    projectId: 'remindrx-631f8',
    authDomain: 'remindrx-631f8.firebaseapp.com',
    storageBucket: 'remindrx-631f8.firebasestorage.app',
    measurementId: 'G-VET1QZD1WD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq2YZFKY5rBVrKD2Tr8DnUPOveoKOM3UI',
    appId: '1:1032931526089:web:36edfae7a5c9c079d8d418',
    messagingSenderId: '1032931526089',
    projectId: 'remindrx-631f8',
    authDomain: 'remindrx-631f8.firebaseapp.com',
    storageBucket: 'remindrx-631f8.firebasestorage.app',
    measurementId: 'G-VK4Q37TQJS',
  );
}
